version: '3.6'
services:
  telemetry_db:
    image: tokend/postgres-ubuntu:9.6
    restart: unless-stopped
    environment:
      - POSTGRES_USER=telemetry
      - POSTGRES_PASSWORD=telemetry
      - POSTGRES_DB=telemetry
      - PGDATA=/pgdata
    volumes:
      - telemetry-data:/pgdata
  hasura:
    image: hasura/graphql-engine:v2.0.4
    ports:
    - "8080:8080"
    restart: always
    environment:
      ## this env var can be used to add the above postgres database to Hasura as a data source. this can be removed/updated based on your needs
      HASURA_GRAPHQL_DATABASE_URL: postgres://telemetry:telemetry@telemetry_db/telemetry?sslmode=disable
      ## enable the console served by server
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true" # set to "false" to disable console
      ## enable debugging mode. It is recommended to disable this in production
      HASURA_GRAPHQL_DEV_MODE: "true"
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
      ## uncomment next line to set an admin secret
      # HASURA_GRAPHQL_ADMIN_SECRET: myadminsecretkey
  bdjuno:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    command: bdjuno parse --home /root/.bdjuno
    volumes:
      ## Modify first path to match configuration file.
      - /root/.bdjuno:/root/.bdjuno
